require 'bundler'
Bundler.require

require './models/Video_Games.rb'

class MyApp < Sinatra::Base

  get '/' do
    erb :index
  end

  post '/results' do
    choice = params["choice"]
    
       @sports= [VideoGame.new("NBA 2K15", "http://gm-cdn.gamezebo.netdna-cdn.com/wp-content/uploads/2014/10/nba-2k15-header.jpg", "Rating: 9/10", "http://www.gamestop.com/browse?nav=16k-3-nba+2k15,28zu0", '<iframe width="560" height="315" src="https://www.youtube.com/embed/BTCFKaq30QM" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("NBA 2K14", "http://s2b20blog.mukyou.com/wp-content/uploads/2015/04/NBA-2K14-Wallpapers-10.jpg", "Rating: 4/5", "http://www.gamestop.com/browse?nav=16k-3-nba+2k14,28zu0", '<iframe width="560" height="315" src="https://www.youtube.com/embed/b0KRfU8tFtU" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("Fifa 14", "http://steamhacks.info/wp-content/uploads/2013/10/fifa-14-crack-download.jpg", "Rating: 9/10", "http://www.gamestop.com/browse?nav=16k-3-fifa+14,28zu0", '<iframe width="560" height="315" src="https://www.youtube.com/embed/APMrtUd4WW8" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("Fifa 15", "http://i.ytimg.com/vi/aSxUW9UF4uw/maxresdefault.jpg", "Rating: 4/5", "http://www.gamestop.com/browse?nav=16k-3-fifa+15,28zu0", '<iframe width="560" height="315" src="https://www.youtube.com/embed/TnTYVT6lwBc" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("Madden NFL 15", "http://cbssports.com/images/blogs/Richard_Sherman_Madden_Curse_Madden_15_Cover.jpg", "Rating: 4/5", "http://www.gamestop.com/browse?nav=16k-3-madden+15,28zu0", '<iframe width="560" height="315" src="https://www.youtube.com/embed/nUiBJy150rg" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("Madden NFL 25", "http://gamerspeek.com/wp-content/uploads/2013/09/Madden-25.jpg", "Rating: 7/10", "http://www.gamestop.com/browse?nav=16k-3-madden+25,28zu0", '<iframe width="560" height="315" src="https://www.youtube.com/embed/vCsMR13TJ9M" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("NBA Live 15", "http://www.get-cracked.com/wp-content/uploads/2015/02/NBA-Live-15-free-cd-key.jpg", "Rating: 5/10", "http://www.gamestop.com/browse?nav=16k-3-nba+live+15,28zu0", '<iframe width="560" height="315" src="https://www.youtube.com/embed/w-8vL1r4pU8" frameborder="0" allowfullscreen></iframe>')]
    @action_and_adventure= [VideoGame.new("Assassin's Creed Unity", "http://www.hacksbook.com/wp-content/uploads/2014/09/assassins_creed_unity.png", "Rating: 7/10", "http://www.gamestop.com/browse?nav=16k-3-assassin+s+creed+unity,28zu0", '<iframe width="560" height="315" src="https://www.youtube.com/embed/ixp1RDIf4O8" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("Batman Arkham Knight", "http://38.media.tumblr.com/1e3ca1ffb5029e8bae95451814bb1f54/tumblr_n1y39wWVCw1r4ppnko1_1280.jpg", "Rating: 9/10", "http://www.gamestop.com/browse?nav=16k-3-batman+arkham+knight,28zu0", '<iframe width="560" height="315" src="https://www.youtube.com/embed/VpXUIh7rlWI" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("Grand Theft Auto V", "http://i.ytimg.com/vi/jl2xNWeujZs/maxresdefault.jpg", "Rating: 5/5", "http://www.gamestop.com/browse?nav=16k-Grand+Theft+Auto+V", '<iframe width="560" height="315" src="https://www.youtube.com/embed/QkkoHAzjnUs" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("Grand Theft Auto San Andreas", "http://s.emuparadise.org/fup/up/150569-Grand_Theft_Auto_-_San_Andreas_(USA)_(v1.03)-1.jpg", "Rating: 4/5", "http://www.gamestop.com/browse?nav=16k-Grand+Theft+Auto+San+Andreas", '<iframe width="420" height="315" src="https://www.youtube.com/embed/u_CbHrBbHNQ" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("Super Mario Bros", "http://i.kinja-img.com/gawker-media/image/upload/kfqicliuawygmhlfpbdy.jpg", "Rating: 8/10", "http://www.gamestop.com/browse?nav=16k-3-super+mario+bros,28zu0", '<iframe width="560" height="315" src="https://www.youtube.com/embed/IQHa4qindfE" frameborder="0" allowfullscreen></iframe>')]
    @cars_and_racing= [VideoGame.new("Mario Cart", "http://mariokart8.nintendo.com/img/fbook.jpg", "Rating: 9/10", "http://www.gamestop.com/browse?nav=16k-3-mario+kart,28zu0", '<iframe width="560" height="315" src="https://www.youtube.com/embed/NA6CAgv6p6g" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("Forza Motorsport 5", "http://static4.gamespot.com/uploads/scale_medium/1197/11970954/2309099-forza5.jpg", "Rating: 9/10", "http://www.gamestop.com/browse?nav=16k-3-forza+motorsport+5,28zu0", '<iframe width="560" height="315" src="https://www.youtube.com/embed/__6lyUbBdWM" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("Grand Theft Auto V", "http://i.ytimg.com/vi/jl2xNWeujZs/maxresdefault.jpg", "Rating: 5/5", "http://www.gamestop.com/browse?nav=16k-Grand+Theft+Auto+V", '<iframe width="560" height="315" src="https://www.youtube.com/embed/QkkoHAzjnUs" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("Driver San Fransisco", "http://images.gameskinny.com/gameskinny/07a9f2c39621aef1c95439b53e3d3eaf.jpg", "Rating: 4/5", "http://www.gamestop.com/browse?nav=16k-Driver+San+Francisco", '<iframe width="560" height="315" src="https://www.youtube.com/embed/htXCOlSzeAQ" frameborder="0" allowfullscreen></iframe>')]
    @first_person_shooter= [VideoGame.new("Call of Duty Black Ops", "http://cdn.akamai.steamstatic.com/steam/apps/42700/header.jpg?t=1379361422", "Rating: 5/5", "http://www.gamestop.com/browse?nav=16k-3-call+of+duty+black+ops,28zu0", '<iframe width="560" height="315" src="https://www.youtube.com/embed/OPTOVQFRggI" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("Call of Duty Black Ops II", "http://gearnuke.com/wp-content/uploads/2014/05/Call-Of-Duty-Black-Ops-II-logo1.jpeg", "Rating: 4/5", "http://www.gamestop.com/browse?nav=16k-Call+of+Duty+Black+Ops+II", '<iframe width="560" height="315" src="https://www.youtube.com/embed/x3tedlWs1XY" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("Call of Duty Modern Warfare 3", "http://donotargue.com/wp-content/uploads/2014/03/call-of-duty-modern-warfare-3-hd-wallpapers-1080p-widescreen-games-photo-call-of-duty-hd-wallpaper.jpg", "Rating: 5/5", "http://www.gamestop.com/browse?nav=16k-Call+of+Duty+Modern+Warfare+3", '<iframe width="560" height="315" src="https://www.youtube.com/embed/1xjCdN_rWCE" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("Call of Duty Advanced Warfare", "http://86bb71d19d3bcb79effc-d9e6924a0395cb1b5b9f03b7640d26eb.r91.cf1.rackcdn.com/wp-content/uploads/2014/11/call-of-duty-advanced-warfare-walkthrough.jpg", "Rating: 4/5", "http://www.gamestop.com/browse?nav=16k-Call+of+Duty+Advanced+Warfare", '<iframe width="560" height="315" src="https://www.youtube.com/embed/sFu5qXMuaJU" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("Call of Duty Ghosts", "http://gearnuke.com/wp-content/uploads/2014/08/135.jpg", "Rating: 4/5", "http://www.gamestop.com/browse?nav=16k-Call+of+Duty+Ghosts", '<iframe width="560" height="315" src="https://www.youtube.com/embed/Zxnx3W-HA18" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("Halo Reach", "http://theaudiospotlight.com/wp-content/uploads/2012/06/halo-reach.jpg", "Rating: 5/5", "http://www.gamestop.com/browse?nav=16k-Halo+Reach", '<iframe width="560" height="315" src="https://www.youtube.com/embed/k9ez7iNjoVg" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("Destiny", "http://cdn2.bigcommerce.com/server100/y7xbit5/product_images/uploaded_images/destiny-gh-website-banner.jpg?t=1409897361", "Rating: 3/5", "http://www.gamestop.com/browse?nav=16k-3-destiny,28zu0", '<iframe width="560" height="315" src="https://www.youtube.com/embed/9ZyQK6kUdWQ" frameborder="0" allowfullscreen></iframe>')]
    @fighting_and_combat= [VideoGame.new("WWE 2K15", "http://www.savecontinue.com/wp-content/uploads/2014/07/NEW2K15H.jpg", "Rating: 2/5", "http://www.gamestop.com/browse?nav=16k-3-wwe+2k15,28zu0", '<iframe width="560" height="315" src="https://www.youtube.com/embed/BBYZ1OJYmtw" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("EA Sports UFC 2", "http://media.idownloadblog.com/wp-content/uploads/2015/04/ea-sports-ufc-1.jpg", "Rating: 7/10", "http://www.gamestop.com/browse?nav=16k-3-ea+sports+ufc+2,28zu0", '<iframe width="560" height="315" src="https://www.youtube.com/embed/dCTk7pCCfG4" frameborder="0" allowfullscreen></iframe>'), VideoGame.new("Mortal Combat X", "http://thisgengaming.com/wp-content/uploads/2015/04/maxresdefault-5.jpg", "Rating: 4/5", "http://www.gamestop.com/browse?nav=16k-Mortal+Kombat", '<iframe width="560" height="315" src="https://www.youtube.com/embed/jSi2LDkyKmI" frameborder="0" allowfullscreen></iframe>')]
  @stealth= [VideoGame.new("Assassin's Creed Unity", "http://www.hacksbook.com/wp-content/uploads/2014/09/assassins_creed_unity.png", "Rating: 7/10", "http://www.gamestop.com/browse?nav=16k-3-assassin+s+creed+unity,28zu0", '<iframe width="560" height="315" src="https://www.youtube.com/embed/ixp1RDIf4O8" frameborder="0" allowfullscreen></iframe>'),
    VideoGame.new("Assassin's Creed Rogue", "http://geekparty.com/wp-content/uploads/2014/08/Assassins-Creed-Rogue1.jpg", "Rating: 3/5", "http://www.gamestop.com/browse?nav=16k-Assassin+s+Creed+Rogue", '<iframe width="560" height="315" src="https://www.youtube.com/embed/RDeyI31pG8A" frameborder="0" allowfullscreen></iframe>'),
    VideoGame.new("Assassin's Creed Black Flag", "http://solvetube.com/wp-content/uploads/2014/11/How-To-Install-Assassins-Creed-4-Black-Flag-Game-Without-Errors.jpg", "Rating: 5/5", "http://www.gamestop.com/browse?nav=16k-Assassin+s+Creed+IV+Black+Flag", '<iframe width="560" height="315" src="https://www.youtube.com/embed/MIHvnTb6HXw" frameborder="0" allowfullscreen></iframe>')]
    @open_world_and_survival= [VideoGame.new("Minecraft", "https://images-eds-ssl.xboxlive.com/image?url=8Oaj9Ryq1G1_p3lLnXlsaZgGzAie6Mnu24_PawYuDYIoH77pJ.X5Z.MqQPibUVTcRY.yavzo7nYP0X88I63UeJxs_ICOvM1iX20FQwMAmM_NGf2PodioxJlXeVtHatYGRJBIPfMhy_BiqqPoi7JdnkTPLMVQUKke7MXg5lM5XcXKfgntlW9iQcqf8zpk76BldA8GgLiMLoy78RsNUyw20Pd_86kNY7GdVNagox9w1XM-&format=jpg", "Rating: 4/5", "http://www.gamestop.com/browse?nav=16k-3-minecraft,28zu0", '<iframe width="560" height="315" src="https://www.youtube.com/embed/aCkE_lk9euY" frameborder="0" allowfullscreen></iframe>')]

  
    
    if choice == "sports"
      @game = @sports.sample
    elsif choice == "action_and_adventure"
      @game = @action_and_adventure.sample
    elsif choice == "cars_and_racing"
      @game = @cars_and_racing.sample
    elsif choice == "first_person_shooter"
      @game = @first_person_shooter.sample
    elsif choice == "fighting_and_combat"
      @game = @fighting_and_combat.sample
    elsif choice == "stealth"
      @game = @stealth.sample
    elsif choice == "open_world_and_survival"
      @game = @open_world_and_survival.sample
    end
    
      @name = @game.name
      @picture = @game.picture
      @rating = @game.rating
      @website = @game.website
      @trailer = @game.trailer
    
    erb :results
end 
    
    

end
